# Generated by Django 5.1.5 on 2025-04-19 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
            preserve_default=False,
        ),
    ]
