# Generated by Django 5.2 on 2025-04-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
