# Generated by Django 5.1.6 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0004_mainmenu_icon_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmenu",
            name="icon_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
