# Generated by Django 5.1.5 on 2025-04-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0006_ownedbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="rate",
        ),
    ]
